### ISSUE TITLE
`getInputProps` returns `disabled` as `undefined` when using muiOptions

### ISSUE THREAD

**Issue by mikemurray** [DairyStateDesigns/reacto-form#8]
The return value from `getInputProps("inventoryInStock", muiOptions)` is...

```
disabled: undefined
name: "inventoryInStock"
onBlur: ƒ onInputValueChange()
onChange: ƒ onInputValueChanging()
value: 9
```

With disabled being `undefined`, this means I have to move my `disabled` prop below the destructuring because explicitly it override the user-defined prop. I'm not sure if this was an intended change in the latest version.

Here are some examples of pre/post 1.5.

Worked in v1.4.2
```jsx
<Input
   disabled={true}
   {...getInputProps("inventoryInStock", muiOptions)}
/>
```

Version in 1.5
```jsx
<Input
   {...getInputProps("inventoryInStock", muiOptions)}
   disabled={true}
/>
```

**Comment by aldeed** [comment]
@mikemurray Adding `disabled` was intentional, though I was thinking of it more as a fix since it was always intended to be working. I can see how it was unintentionally confusing.

In general, it seems best to me that `...getInputProps` is always the first prop in the list.

If you're disabling one field, you'll need to set the prop after as in your example. But if you're disabling the whole form, you should let reacto-form do it for you by passing `isReadOnly` option to the hook. It can be set to a boolean or to a function that takes the current form data and returns a boolean. I see now that this isn't documented in the readme, so I'll document it.

**Comment by aldeed** [comment]
Added to readme
